import os
import subprocess
from datetime import datetime
import re

save_to = "/root/scripts/updater_list_for_mikrotik"
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Відкриття файлу для запису даних
combined_rsc_path = os.path.join(save_to, "combined.rsc")

# Словник для зберігання IP адрес і їх коментарів
ip_dict = {}

# Функція для додавання або оновлення IP в словнику
def add_or_update_ip(ip, comment):
    if ip in ip_dict:
        ip_dict[ip].add(comment)  # Додавання коментаря до існуючого IP
    else:
        ip_dict[ip] = {comment}  # Створення нового запису з коментарем

# DShield
dshield_output = subprocess.run(["wget", "-q", "-O", "-", "http://feeds.dshield.org/block.txt"], capture_output=True, text=True)
dshield_data = dshield_output.stdout.split("\n")
for line in dshield_data:
    parts = line.split("\t")
    if len(parts) >= 3 and parts[0].count('.') == 3:  # Перевірка на правильність IP
        start_ip = parts[0]
        mask = parts[2]
        add_or_update_ip(f"{start_ip}/{mask}", "Auto_address_List")

# Spamhaus DROP
spamhaus_output = subprocess.run(["wget", "-q", "-O", "-", "https://www.spamhaus.org/drop/drop.txt"], capture_output=True, text=True)
spamhaus_data = spamhaus_output.stdout.split("\n")
for line in spamhaus_data:
    ip_match = re.search(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}\b', line)
    if ip_match:
        ip = ip_match.group(0)
        add_or_update_ip(ip, "Auto_address_List")

# Spamhaus EDROP
spamhaus_output = subprocess.run(["wget", "-q", "-O", "-", "https://www.spamhaus.org/drop/edrop.txt"], capture_output=True, text=True)
spamhaus_data = spamhaus_output.stdout.split("\n")
for line in spamhaus_data:
    ip_match = re.search(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}\b', line)
    if ip_match:
        ip = ip_match.group(0)
        add_or_update_ip(ip, "Auto_address_List")

# Danger.rulez.sk
blist_output = subprocess.run(["wget", "-q", "-O", "-", "https://danger.rulez.sk/projects/bruteforceblocker/blist.php"], capture_output=True, text=True)
blist_data = blist_output.stdout.split("\n")
for line in blist_data:
    ip_match = re.search(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', line)
    if ip_match:
        ip = ip_match.group(0)
        add_or_update_ip(ip, "Bruteforce_Blocker")

# Запис у файл
with open(combined_rsc_path, "w") as combined_rsc:
    combined_rsc.write(f"# Generated by Serp07 on {now}\n")
    combined_rsc.write("/ip firewall address-list\n")
    for ip, comments in ip_dict.items():
        combined_rsc.write(f"add list=blacklist address={ip} comment={' & '.join(comments)}\n")


# Додавання файлу в Git та відправлення на GitHub
os.chdir(save_to)  # Зміна поточного каталогу на той, де знаходиться combined.rsc
subprocess.run(["git", "add", "combined.rsc"])  # Додати файл combined.rsc до Git
subprocess.run(["git", "commit", "-m", "Update combined.rsc"])  # Зробити коміт з оновленнями
subprocess.run(["git", "push"])  # Відправити оновлення на GitHub
